# Generated by Django 5.1.4 on 2026-09-06 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('city', models.CharField(choices=[('pokhara', 'Pokhara'), ('kathmandu', 'Kathmandu')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lots/')),
                ('hourly_rate_bike', models.PositiveIntegerField(default=20, help_text='NPR per hour')),
                ('hourly_rate_car', models.PositiveIntegerField(default=50, help_text='NPR per hour')),
                ('opening_time', models.TimeField(default='06:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('is_24_hours', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=True)),
                ('has_covered_parking', models.BooleanField(default=False)),
                ('has_ev_charging', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(help_text='e.g. A1, B12', max_length=10)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike / Scooter'), ('car', 'Car / SUV')], default='car', max_length=10)),
                ('floor', models.CharField(default='Ground', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='available', max_length=12)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['lot', 'floor', 'slot_number'],
                'unique_together': {('lot', 'slot_number')},
            },
        ),
    ]
