# Generated by Django 5.1.4 on 2026-09-06 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, help_text='e.g. Lakeside, Pokhara', max_length=255)),
                ('default_vehicle_type', models.CharField(choices=[('bike', 'Bike / Scooter'), ('car', 'Car'), ('suv', 'SUV / Jeep'), ('van', 'Van / Micro')], default='car', max_length=10)),
                ('default_vehicle_number', models.CharField(blank=True, help_text='e.g. GA 2 PA 1234', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
